export const navbar = {
  icon: "/icons/images.png",
  field: ["Templates", "Design Kits", "MUI X"],
};
export const sidebar = {
  search: {
    heading: "SEARCH",
    type: "text",
    placeholder: "Search for templates",
  },
  select: [
    {
      key: "framework",
      heading: "Frameworks",
      options: [
        "React 18",
        "Next.js",
        "Next.js (App Router)",
        "Vite",
        "Remix",
        "Create React App",
      ],
    },
    {
      key: "ui_framework",
      heading: "UI Frameworks",
      options: ["Material UI", "Joy UI", "Base UI", "Tailwind CSS"],
    },
    {
      key: "categories",
      heading: "Categories",
      options: [
        "Dashboard",
        "E-commerce",
        "Landing Page",
        "Blog",
        "Portfolio",
        "Admin",
        "E-commerce Admin",
        "Business",
      ],
    },
    {
      key: "resources",
      heading: "Resources",
      options: [
        "Fullstack Boilerplates",
        "UI Kits & Components",
        "Templates & Themes",
      ],
    },
    {
      key: "template_types",
      heading: "Template Types",
      options: ["Admin & Dashboard", "Landing & Corporate", "E-commerce"],
    },
  ],
};
export const head = {
  heading: "Templates",
  para: "A collection of 4.5 average rating templates, selected and curated by MUI's team of maintainers to get your projects up and running today.",
  sort: {
    name: "SORT BY :",
    options: [
      "Highest Rated",
      "Most Popular",
      "Newest",
      "Price: Low to High",
      "Price: High to Low",
      "A-Z",
      "Z-A",
    ],
  },
};
export const template = {
  data: [
    {
      id: 1,
      image:
        "https://topcode.vn/source-code/minimal-client-and-admin-dashboard-47678.htm",
      name: "Minimal - Client and Admin Dashboard",
      price: "$69",
      category: "Dashboard",
      description:
        "A minimalistic client and admin dashboard with a clean UI and robust features.",
      features: [
        "Responsive design",
        "Dark & light mode",
        "Customizable components",
        "Analytics dashboard",
        "Multi-user authentication",
      ],
      technologies: ["React", "Material UI", "Next.js"],
      rating: 4.5,
      reviews: 120,
      livePreview: "https://minimal-admin-demo.com",
      documentation: "https://docs.minimal-dashboard.com",
      author: "MinimalUI Inc.",
    },
    {
      id: 2,
      image:
        "https://reactcrm.us/product/devias-kit-pro-client-admin-dashboard/",
      name: "Devias Kit Pro - Client and Admin Dashboard",
      price: "$69",
      category: "Dashboard",
      description:
        "A powerful client and admin dashboard template built for scalability and ease of use.",
      features: [
        "Modern UI",
        "Role-based access control",
        "Prebuilt dashboard widgets",
        "Customizable charts",
        "Authentication system",
      ],
      technologies: ["React", "Material UI", "Node.js"],
      rating: 4.7,
      reviews: 180,
      livePreview: "https://devias-kit-pro-demo.com",
      documentation: "https://docs.devias-kit.com",
      author: "Devias Labs",
    },
    {
      id: 3,
      image: "https://maccarianagency.com/",
      name: "theFront - Multipurpose Template + UI Kit",
      price: "$49",
      category: "Multipurpose UI Kit",
      description:
        "A flexible and feature-rich UI kit for building modern web applications.",
      features: [
        "Prebuilt landing pages",
        "E-commerce support",
        "SEO-friendly",
        "Blog integration",
        "Custom form elements",
      ],
      technologies: ["React", "Next.js", "Bootstrap"],
      rating: 4.6,
      reviews: 95,
      livePreview: "https://thefront-demo.com",
      documentation: "https://docs.thefront.com",
      author: "Maccarian Agency",
    },
    {
      id: 4,
      image: "https://mui.com/store/items/berry-react-material-admin/",
      name: "Berry - React Material UI Dashboard Template",
      price: "$69",
      category: "Dashboard",
      description:
        "A sleek and powerful admin dashboard built with Material UI and React.",
      features: [
        "Material UI components",
        "Easy customization",
        "Dark mode support",
        "Data visualization tools",
        "User role management",
      ],
      technologies: ["React", "Material UI", "Redux"],
      rating: 4.8,
      reviews: 210,
      livePreview: "https://berry-dashboard-demo.com",
      documentation: "https://docs.berry-dashboard.com",
      author: "CodedThemes",
    },
    {
      id: 5,
      image:
        "https://reactcrm.us/product/zone-multipurpose-landing-page-ui-kit/",
      name: "Zone - Multipurpose Landing Page + UI Kit",
      price: "$59",
      category: "Landing Page UI Kit",
      description:
        "A comprehensive UI kit for building high-converting landing pages.",
      features: [
        "SEO-optimized pages",
        "Multiple prebuilt templates",
        "Fully responsive",
        "Integration with email marketing tools",
        "Custom UI components",
      ],
      technologies: ["React", "Next.js", "Tailwind CSS"],
      rating: 4.4,
      reviews: 85,
      livePreview: "https://zone-landing-demo.com",
      documentation: "https://docs.zone-ui-kit.com",
      author: "Zone UI Team",
    },
    {
      id: 6,
      image:
        "https://mui.com/store/items/mantis-react-admin-dashboard-template/",
      name: "Mantis - React Material UI Dashboard Template",
      price: "$69",
      category: "Dashboard",
      description:
        "A professional and modern admin dashboard template with Material UI design.",
      features: [
        "Material UI components",
        "Light & dark mode",
        "Advanced charts",
        "Authentication system",
        "Customizable widgets",
      ],
      technologies: ["React", "Material UI", "Redux Toolkit"],
      rating: 4.7,
      reviews: 160,
      livePreview: "https://mantis-dashboard-demo.com",
      documentation: "https://docs.mantis-dashboard.com",
      author: "CodedThemes",
    },
    {
      id: 7,
      image: "https://mui.com/store/items/devias-kit-pro/",
      name: "Bazaar Pro - Multipurpose Next.js Ecommerce Template",
      price: "$69",
      category: "Ecommerce",
      description:
        "A feature-rich ecommerce template built for modern online stores.",
      features: [
        "Optimized for performance",
        "Mobile-friendly UI",
        "Product catalog management",
        "Shopping cart & checkout",
        "Payment gateway integration",
      ],
      technologies: ["React", "Next.js", "Tailwind CSS"],
      rating: 4.5,
      reviews: 140,
      livePreview: "https://bazaar-pro-demo.com",
      documentation: "https://docs.bazaar-pro.com",
      author: "Bazaar UI Team",
    },
    {
      id: 8,
      image: "https://mira.bootlab.io/",
      name: "Mira Pro - React Material UI Admin Dashboard",
      price: "$69",
      category: "Dashboard",
      description:
        "A high-performance admin dashboard template built with Material UI and React.",
      features: [
        "Dynamic dashboard components",
        "Real-time data visualization",
        "Authentication & authorization",
        "Easy theming support",
        "Multi-language support",
      ],
      technologies: ["React", "Material UI", "Redux Saga"],
      rating: 4.6,
      reviews: 175,
      livePreview: "https://mira-pro-demo.com",
      documentation: "https://docs.mira-dashboard.com",
      author: "Bootlab",
    },
    {
      id: 9,
      image: "https://mantisdashboard.io/",
      name: "Materio - Next.js Admin Template",
      price: "$69",
      category: "Dashboard",
      description:
        "A professional and modern Next.js-based admin template for web applications.",
      features: [
        "Next.js 13 support",
        "Server-side rendering",
        "GraphQL & REST API integration",
        "Modular architecture",
        "Prebuilt UI components",
      ],
      technologies: ["React", "Next.js", "GraphQL"],
      rating: 4.8,
      reviews: 190,
      livePreview: "https://materio-dashboard-demo.com",
      documentation: "https://docs.materio-dashboard.com",
      author: "Materio UI Team",
    },
    {
      id: 10,
      image: "https://mui.com/store/items/paperbase/",
      name: "uifort - React Client and Admin Dashboard Template",
      price: "$69",
      category: "Dashboard",
      description:
        "A highly customizable client and admin dashboard template with a sleek UI.",
      features: [
        "Fully responsive layout",
        "User-friendly dashboard",
        "Easily extendable components",
        "Data analytics integration",
        "Secure authentication system",
      ],
      technologies: ["React", "Material UI", "Firebase"],
      rating: 4.5,
      reviews: 130,
      livePreview: "https://uifort-dashboard-demo.com",
      documentation: "https://docs.uifort-dashboard.com",
      author: "UIFort Team",
    },

    {
      id: 11,
      image:
        "https://mui.com/store/items/mantis-react-admin-dashboard-template/",
      name: "UI Foundations Kit - SaaS Dashboard Template",
      price: "$49",
      category: "Dashboard",
      description:
        "A lightweight and flexible dashboard template for SaaS applications.",
      features: [
        "Multi-tenant support",
        "Customizable UI elements",
        "User management system",
        "Analytics & reporting tools",
        "Integrated notifications system",
      ],
      technologies: ["React", "Next.js", "Chakra UI"],
      rating: 4.4,
      reviews: 110,
      livePreview: "https://ui-foundations-demo.com",
      documentation: "https://docs.ui-foundations.com",
      author: "Foundations UI",
    },
    {
      id: 12,
      image: "https://webbee.maccarianagency.com/",
      name: "Webbee - Multipurpose Landing Page UI Kit",
      price: "$59",
      category: "Landing Page UI Kit",
      description:
        "A beautifully designed UI kit for building modern and responsive landing pages.",
      features: [
        "SEO-friendly components",
        "Prebuilt page templates",
        "Cross-browser compatibility",
        "Google Fonts integration",
        "Easily customizable styles",
      ],
      technologies: ["React", "Next.js", "Bootstrap"],
      rating: 4.6,
      reviews: 125,
      livePreview: "https://webbee-demo.com",
      documentation: "https://docs.webbee-ui.com",
      author: "Maccarian Agency",
    },
    {
      id: 13,
      image: "https://bazar-react.vercel.app/",
      name: "UKO - Client and Admin Dashboard (Next.js and Vite)",
      price: "$49",
      category: "Dashboard",
      description:
        "A modern and performant dashboard template for client and admin applications.",
      features: [
        "Vite-powered fast loading",
        "Light & dark mode support",
        "Multi-language support",
        "GraphQL API integration",
        "Role-based access control",
      ],
      technologies: ["React", "Next.js", "Vite"],
      rating: 4.7,
      reviews: 140,
      livePreview: "https://uko-dashboard-demo.com",
      documentation: "https://docs.uko-dashboard.com",
      author: "UKO UI Team",
    },
    {
      id: 14,
      image:
        "https://reactcrm.us/product/devias-kit-pro-client-admin-dashboard/",
      name: "Otis Admin PRO - Material Dashboard for React",
      price: "$69",
      category: "Dashboard",
      description:
        "A clean and feature-rich React admin dashboard template with Material UI.",
      features: [
        "Prebuilt Material UI components",
        "Advanced charting tools",
        "Authentication & authorization",
        "Dark & light mode",
        "Optimized for performance",
      ],
      technologies: ["React", "Material UI", "Redux"],
      rating: 4.8,
      reviews: 165,
      livePreview: "https://otis-admin-pro-demo.com",
      documentation: "https://docs.otis-admin.com",
      author: "Otis UI Team",
    },
    {
      id: 15,
      image:
        "https://reactcrm.us/product/zone-multipurpose-landing-page-ui-kit/",
      name: "Modernize - React and Next.js Admin Template",
      price: "$49",
      category: "Dashboard",
      description:
        "A sleek and modern admin dashboard built with React and Next.js.",
      features: [
        "Server-side rendering (SSR)",
        "Customizable UI elements",
        "Advanced authentication system",
        "Prebuilt dashboard layouts",
        "Integration with third-party APIs",
      ],
      technologies: ["React", "Next.js", "Material UI"],
      rating: 4.5,
      reviews: 135,
      livePreview: "https://modernize-dashboard-demo.com",
      documentation: "https://docs.modernize-dashboard.com",
      author: "Modernize UI Team",
    },
    {
      id: 16,
      image: "https://mui.com/store/items/coded-theme-react-dashboard/",
      name: "CodedTheme React Dashboard Pro",
      price: "$69",
      category: "Dashboard",
      description:
        "A modern admin dashboard with prebuilt Material UI components and seamless integration.",
      features: [
        "Material UI components",
        "Role-based authentication",
        "Dark and light mode",
        "Dashboard analytics",
        "Prebuilt UI elements",
      ],
      technologies: ["React", "Material UI", "Redux"],
      rating: 4.7,
      reviews: 145,
      livePreview: "https://codedtheme-dashboard-demo.com",
      documentation: "https://docs.codedtheme-dashboard.com",
      author: "CodedTheme",
    },
    {
      id: 17,
      image: "https://justboil.me/tailwind-dashboard/",
      name: "JustBoil - Tailwind Admin Dashboard",
      price: "$59",
      category: "Dashboard",
      description:
        "A lightweight admin dashboard template built using Tailwind CSS and React.",
      features: [
        "Tailwind CSS for styling",
        "Dark mode support",
        "Modular components",
        "Authentication system",
        "Custom widgets",
      ],
      technologies: ["React", "Tailwind CSS", "Vite"],
      rating: 4.5,
      reviews: 120,
      livePreview: "https://justboil-dashboard-demo.com",
      documentation: "https://docs.justboil-dashboard.com",
      author: "JustBoil Team",
    },
    {
      id: 18,
      image: "https://next-commerce.vercel.app/",
      name: "Next Commerce - Full E-commerce Solution",
      price: "$79",
      category: "Ecommerce",
      description:
        "A fully functional e-commerce template with product management and payment integrations.",
      features: [
        "Full e-commerce functionality",
        "Product catalog & filtering",
        "Shopping cart & checkout",
        "Payment gateway integration",
        "SEO-friendly pages",
      ],
      technologies: ["React", "Next.js", "Tailwind CSS"],
      rating: 4.6,
      reviews: 175,
      livePreview: "https://next-commerce-demo.com",
      documentation: "https://docs.next-commerce.com",
      author: "Commerce Labs",
    },
    {
      id: 19,
      image:
        "https://wrapbootstrap.com/theme/angle-bootstrap-admin-template-WB04HF123",
      name: "Angle - React Admin Template",
      price: "$69",
      category: "Dashboard",
      description:
        "A multipurpose React admin dashboard template with a clean and modern UI.",
      features: [
        "Bootstrap 5 & React support",
        "Multiple layout options",
        "Prebuilt dashboard widgets",
        "Authentication system",
        "Data visualization tools",
      ],
      technologies: ["React", "Bootstrap", "Redux"],
      rating: 4.8,
      reviews: 195,
      livePreview: "https://angle-dashboard-demo.com",
      documentation: "https://docs.angle-dashboard.com",
      author: "WrapBootstrap",
    },
    {
      id: 20,
      image: "https://themesberg.com/product/ui-kits/volt-react-dashboard",
      name: "Volt React - Free Bootstrap Dashboard",
      price: "Free",
      category: "Dashboard",
      description:
        "A free and open-source React dashboard template built with Bootstrap.",
      features: [
        "Bootstrap-based design",
        "Minimalistic UI",
        "Authentication system",
        "Customizable components",
        "Fully responsive layout",
      ],
      technologies: ["React", "Bootstrap", "Redux"],
      rating: 4.3,
      reviews: 85,
      livePreview: "https://volt-react-dashboard-demo.com",
      documentation: "https://docs.volt-dashboard.com",
      author: "Themesberg",
    },
    {
      id: 21,
      image: "https://mui.com/store/items/materially-react/",
      name: "Materially - React Admin Dashboard",
      price: "$69",
      category: "Dashboard",
      description:
        "A Material UI-based admin dashboard template with powerful features.",
      features: [
        "Material UI design",
        "Authentication system",
        "Charts & graphs",
        "Multi-language support",
        "Customizable widgets",
      ],
      technologies: ["React", "Material UI", "Redux"],
      rating: 4.7,
      reviews: 150,
      livePreview: "https://materially-dashboard-demo.com",
      documentation: "https://docs.materially-dashboard.com",
      author: "CodedThemes",
    },
    {
      id: 22,
      image: "https://vuexy.react.demo/",
      name: "Vuexy - React Admin Dashboard",
      price: "$79",
      category: "Dashboard",
      description:
        "A premium React admin template with a modern UI and flexible components.",
      features: [
        "Fully responsive design",
        "Role-based authentication",
        "Multiple dashboards",
        "Dark & light mode",
        "Built-in UI components",
      ],
      technologies: ["React", "Bootstrap", "Redux Toolkit"],
      rating: 4.9,
      reviews: 230,
      livePreview: "https://vuexy-dashboard-demo.com",
      documentation: "https://docs.vuexy-dashboard.com",
      author: "Pixinvent",
    },
    {
      id: 23,
      image: "https://sneat.react.demo/",
      name: "Sneat - MUI Admin Template",
      price: "$59",
      category: "Dashboard",
      description:
        "A Material UI-based admin dashboard template with clean code structure.",
      features: [
        "Material UI components",
        "Advanced charts",
        "Prebuilt UI elements",
        "User management system",
        "Mobile-friendly layout",
      ],
      technologies: ["React", "Material UI", "Redux"],
      rating: 4.6,
      reviews: 190,
      livePreview: "https://sneat-dashboard-demo.com",
      documentation: "https://docs.sneat-dashboard.com",
      author: "ThemeSelection",
    },
    {
      id: 24,
      image: "https://startbootstrap.com/theme/sb-admin-react",
      name: "SB Admin - Free React Admin Template",
      price: "Free",
      category: "Dashboard",
      description: "A free and open-source admin dashboard template for React.",
      features: [
        "Bootstrap-based design",
        "Simple and lightweight",
        "Responsive layout",
        "Custom UI components",
        "Authentication support",
      ],
      technologies: ["React", "Bootstrap", "Redux"],
      rating: 4.2,
      reviews: 90,
      livePreview: "https://sb-admin-react-demo.com",
      documentation: "https://docs.sb-admin-react.com",
      author: "StartBootstrap",
    },
    {
      id: 25,
      image: "https://coreui.io/react/",
      name: "CoreUI - React Admin Template",
      price: "$49",
      category: "Dashboard",
      description:
        "A feature-rich admin template built with CoreUI components.",
      features: [
        "Modular UI components",
        "Dark mode support",
        "Custom form elements",
        "Charts & graphs",
        "Authentication system",
      ],
      technologies: ["React", "Bootstrap", "Redux"],
      rating: 4.4,
      reviews: 125,
      livePreview: "https://coreui-dashboard-demo.com",
      documentation: "https://docs.coreui-dashboard.com",
      author: "CoreUI Team",
    },
    {
      id: 26,
      image: "https://adminmart.com/product/poco-react-admin/",
      name: "Poco - React Admin Dashboard",
      price: "$59",
      category: "Dashboard",
      description: "A clean and modern React admin dashboard template.",
      features: [
        "Multiple dashboard layouts",
        "Prebuilt UI components",
        "Advanced data tables",
        "Dark & light mode",
        "Easy integration with APIs",
      ],
      technologies: ["React", "Bootstrap", "Redux"],
      rating: 4.5,
      reviews: 135,
      livePreview: "https://poco-dashboard-demo.com",
      documentation: "https://docs.poco-dashboard.com",
      author: "AdminMart",
    },
    {
      id: 27,
      image: "https://mui.com/store/items/fuse-react/",
      name: "Fuse - React Admin Template",
      price: "$79",
      category: "Dashboard",
      description:
        "A flexible and powerful Material UI admin template for React applications.",
      features: [
        "Material UI-based design",
        "Authentication & authorization",
        "Multi-language support",
        "Custom themes",
        "Modular code structure",
      ],
      technologies: ["React", "Material UI", "Redux"],
      rating: 4.8,
      reviews: 210,
      livePreview: "https://fuse-dashboard-demo.com",
      documentation: "https://docs.fuse-dashboard.com",
      author: "ThemeForest",
    },
    {
      id: 28,
      image: "https://soft-ui-dashboard-react.creative-tim.com/",
      name: "Soft UI - React Dashboard",
      price: "$69",
      category: "Dashboard",
      description:
        "A stylish and modern React admin template with Soft UI design.",
      features: [
        "Soft UI design system",
        "Fully responsive layout",
        "User-friendly dashboard",
        "Customizable UI components",
        "Authentication system",
      ],
      technologies: ["React", "Material UI", "Redux"],
      rating: 4.7,
      reviews: 175,
      livePreview: "https://soft-ui-dashboard-demo.com",
      documentation: "https://docs.soft-ui-dashboard.com",
      author: "Creative Tim",
    },
    {
      id: 29,
      image: "https://dorsin-react.firebaseapp.com/",
      name: "Dorsin - React Landing Page Template",
      price: "$49",
      category: "Landing Page",
      description:
        "A sleek and elegant landing page template built with React and Bootstrap.",
      features: [
        "One-page layout",
        "SEO-friendly structure",
        "Fully responsive",
        "Easy customization",
        "Prebuilt UI components",
      ],
      technologies: ["React", "Bootstrap", "Redux"],
      rating: 4.5,
      reviews: 110,
      livePreview: "https://dorsin-landing-demo.com",
      documentation: "https://docs.dorsin-landing.com",
      author: "Themesbrand",
    },
    {
      id: 30,
      image: "https://hously-react.vercel.app/",
      name: "Hously - Real Estate React Template",
      price: "$59",
      category: "Real Estate",
      description:
        "A professional real estate template designed for property listings and management.",
      features: [
        "Real estate property listing",
        "Map integration",
        "Advanced search filters",
        "User authentication",
        "Mobile-friendly UI",
      ],
      technologies: ["React", "Next.js", "Tailwind CSS"],
      rating: 4.6,
      reviews: 130,
      livePreview: "https://hously-realestate-demo.com",
      documentation: "https://docs.hously-realestate.com",
      author: "Shreethemes",
    },
  ],
};
